<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 2.11.11.3 setup script by Michal Čihař <michal@cihar.com>
 * Version: $Id$
 * Date: Thu, 17 Dec 2015 09:15:06 GMT
 */


$cfg['blowfish_secret'] = 'myskafafafaf'; /* YOU MUST FILL IN THIS FOR COOKIE AUTH! */

/* Servers configuration */
$i = 0;

/* Server xxx.my3w.com (config:xxx) [1] */
$i++;
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['host'] = 'hdm121115144.my3w.com';
$cfg['Servers'][$i]['extension'] = 'mysql';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['controluser'] = 'hdm121115144';
$cfg['Servers'][$i]['controlpass'] = 'shenjia1314520';
$cfg['Servers'][$i]['user'] = 'hdm121115144';
$cfg['Servers'][$i]['password'] = 'shenjia1314520';

$cfg['Servers'][$i]['AllowDeny']['order'] = '';

$cfg['Servers'][$i]['AllowDeny']['rules'] = array();



/* End of servers configuration */

?>
